FROM nginx:1.27-alpine

RUN rm -f /etc/nginx/conf.d/default.conf

COPY deploy/nginx/00-switchboard.conf /etc/nginx/conf.d/00-switchboard.conf

RUN mkdir -p /etc/nginx/conf.d && \
    touch /etc/nginx/conf.d/switchboard.generated.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
