// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Config"
                        }
                    }
                }
            }
        },
        "/api/containers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "List containers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Container"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "summary": "WebSocket stream",
                "responses": {}
            }
        }
    },
    "definitions": {
        "container.PortSummary": {
            "type": "object",
            "properties": {
                "IP": {
                    "description": "Host IP address that the container's port is mapped to",
                    "allOf": [
                        {
                            "$ref": "#/definitions/netip.Addr"
                        }
                    ]
                },
                "PrivatePort": {
                    "description": "Port on the container\nRequired: true",
                    "type": "integer"
                },
                "PublicPort": {
                    "description": "Port exposed on the host",
                    "type": "integer"
                },
                "Type": {
                    "description": "type\nRequired: true\nEnum: [\"tcp\",\"udp\",\"sctp\"]",
                    "type": "string"
                }
            }
        },
        "main.Config": {
            "type": "object",
            "properties": {
                "defaults": {
                    "$ref": "#/definitions/main.Defaults"
                },
                "hosts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Host"
                    }
                },
                "proxy_mappings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "main.Container": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/container.PortSummary"
                    }
                },
                "state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "main.Defaults": {
            "type": "object",
            "properties": {
                "base_domain": {
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                }
            }
        },
        "main.Host": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tls": {
                    "$ref": "#/definitions/main.TLSConfig"
                }
            }
        },
        "main.TLSConfig": {
            "type": "object",
            "properties": {
                "ca": {
                    "type": "string"
                },
                "cert": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "netip.Addr": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8069",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Switchboard Backend API",
	Description:      "Multi-host Docker monitoring API for container status and proxy mappings.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
